from ..Effects import *

# Legato slide
fx = FxList.new("leg", "leg", {"leg":0, "sus":1 }, order = 0, tag="envelope")
fx.add("osc = osc * XLine.ar(Rand(0.5,1.5)*abs(leg),1,0.05*sus)")
fx.save()

fx = FxList.new("glide", "glide", {"glide": 0, "glidedur": 0.05}, order=0, tag="pitch")
fx.add("osc = Line.kr(start: (osc * glide).clip(-50,22000), end: osc, dur: glidedur)")
fx.save()

fx = FxList.new("glide2", "glissandoriginal", {"glide2": 0, "glide2dur": 0.5, "sus": 1}, order=0, tag="pitch")
fx.add("osc = osc * EnvGen.ar(Env([1, 1, (1.059463**glide2)], [sus*glide2dur, sus*(1-glide2dur)]))")
fx.save()


# Lpf slide
fx = FxList.new('spf','SLPF', {'spf': 0, 'spr': 1, 'spfslide':1, 'spfend':15000}, order=2, tag="filter")
fx.add_var("spfenv")
fx.add('spfenv = EnvGen.ar(Env.new([spf, spfend], [spfslide]))')
fx.add('osc = RLPF.ar(osc, spfenv, spr)')
fx.save()

# Test FX
fx = FxList.new('test','test', {'test': 0, 'testa': 0, 'testb': 0, 'testc': 0, 'testd': 0}, order=2)
fx.doc("Test Fx")
fx.add('osc = osc*test')
fx.save()

# MoogLPF
fx = FxList.new('mpf','MoogFF', {'mpf': 0, 'mpr': 0}, order=2, tag="filter")
fx.doc("MoogFF filter")
fx.add('osc = MoogFF.ar(osc, mpf, mpr,0,1)')
fx.save()

# DFM1 LPF
fx = FxList.new('dfm','DFM1', {'dfm': 1000, 'dfmr': 0.1, 'dfmd': 1}, order=2, tag="filter")
fx.doc("DFM1 filter")
fx.add('osc = DFM1.ar(osc, dfm, dfmr, dfmd,0.0)')
fx.save()

# VALadder filter
fx = FxList.new('valad', 'VALadder', {'valad': 500, 'valadr': 0.3, 'valadd': 5, 'valadt': 0, 'valadc': 0.2}, order=2, tag="filter")
fx.doc("VALadder filter")
fx.add('osc = VALadder.ar(osc*0.4, valad, valadr, valadd,valadt)')
fx.add('osc = Compander.ar(osc, osc, valadc, 1, 0.1, 0.01, 0.1 )')
fx.save()

# VADiode filter
fx = FxList.new('vadiod', 'VADiodeFilter', {'vadiod': 500, 'vadiodr': 0.5, 'vadiodd': 0.5, 'vadiodc': 0.3}, order=2, tag="filter")
fx.doc("VADiode filter")
fx.add('osc = VADiodeFilter.ar(osc*0.5, vadiod, vadiodr, vadiodd)')
fx.add('osc = Compander.ar(osc, osc, vadiodc, 1, 0.1, 0.01, 0.1 )')
fx.save()

fx = FxList.new('vakorg', 'VAKorg', {'vakorg': 500, 'vakorgr': 0.5, 'vakorgd': 0.5, 'vakorgt': 0, 'vakorgc': 0.3}, order=2, tag="filter")
fx.doc("VAKorg filter")
fx.add('osc = VAKorg35.ar(osc*0.4, vakorg, vakorgr, vakorgd,vakorgt)')
fx.add('osc = Compander.ar(osc, osc, vakorgc, 1, 0.1, 0.01, 0.1 )')
fx.save()

# daFunk filter
fx = FxList.new('dafilter', 'DafunkFilter', {'dafilter': 1200, 'dastart': 250, 'darel': 0.2, 'darq': 0.5, 'datype': 0, 'sus': 1}, order=2, tag="filter")
fx.doc("Dafunk Filter")
fx.add_var("env");
fx.add_var("filGen");
fx.add("env = EnvGen.ar(Env.adsr(0.3, 0.2, sus, darel);, Line.kr(1.0, 0.0, sus/2), doneAction:2)")
fx.add("filGen = EnvGen.ar(Env.adsr(0.4, 0.5, 0.2, 0.5);, Line.kr(1.0, 0.0, sus/2), levelScale: dafilter)")
fx.add("osc = SelectX.ar(datype, [BPF.ar(osc, dastart + filGen, darq), BRF.ar(osc, dastart + filGen, darq)])")
fx.add("osc = (osc.clip2(0.007) * 24).distort()")
fx.save()



fx = FxList.new("fm_sin", "FrequencyModulationSine", {"fm_sin":0, "fm_sin_i":1}, order=0, tag="modulation")
fx.add("osc = osc + (SinOsc.kr(osc*fm_sin, 0, fm_sin_i * osc))")
fx.save()

fx = FxList.new("fm_saw", "FrequencyModulationSaw", {"fm_saw":0.5, "fm_saw_i":0.7}, order=0, tag="modulation")
fx.add("osc = osc + (LFSaw.kr(osc * fm_saw, 0, fm_saw_i * osc))")
fx.save()

fx = FxList.new("fm_pulse", "FrequencyModulationPulse", {"fm_pulse":0, "fm_pulse_i":1}, order=0, tag="modulation")
fx.add("osc = osc + (LFPulse.kr(osc * fm_pulse, 0, 0, fm_pulse_i * osc))")
fx.save()

#Dist mod
fx = FxList.new('disto', 'disto_mod', {'disto': 0, 'smooth': 0.3, 'distomix': 1}, order=1, tag="distortion")
fx.add("osc = LinXFade2.ar(CrossoverDistortion.ar(osc, amp:0.5*disto, smooth:smooth),  osc, 1-distomix)")
fx.save()

fx = FxList.new('idist', 'idist', {'idist': 0}, order=1, tag="distortion")
fx.add("osc = LinXFade2.ar(InsideOut.ar(osc,0.4), osc, 1-idist)")
fx.add("osc = LeakDC.ar(osc)")
fx.save()

fx = FxList.new('noiz','noiz', {'noiz': 0, 'noizr': 1, 'noizt': 0, 'sus': 1}, order=1, tag="distortion")
fx.doc("Noize Fx")
fx.add_var("noizType")
fx.add_var("env")
fx.add('env=EnvGen.ar(Env.perc(attackTime: 0,releaseTime: noizr*sus, level: noiz,curve: \linear), doneAction: 0)')
fx.add('noizType = Select.ar(noizt, [BrownNoise.ar(0.1), WhiteNoise.ar(0.1), ClipNoise.ar(0.1),	GrayNoise.ar(0.1), PinkNoise.ar(0.1)])')
fx.add('osc = osc + (noizType * env)')
fx.save()


#New Chop, with wave select :
#chopwave = (0: Pulse, 1: Tri, 2: Saw, 3: Sin, 4: Parabolic )
# and chopi = oscillator phase
fx = FxList.new('chop', 'chop', {'chop': 0, 'sus': 1, 'chopmix': 1, 'chopwave': 0, 'chopi': 0}, order=2, tag="modulation")
fx.add("osc = SelectX.ar(chopmix, [osc, osc * SelectX.kr(chopwave, [LFPulse.kr(chop / sus, iphase:chopi, add: 0.01), LFTri.kr(chop / sus, iphase:chopi, add: 0.01), LFSaw.kr(chop / sus, iphase:chopi, add: 0.01), FSinOsc.kr(chop / sus, iphase:chopi, add: 0.01), LFPar.kr(chop / sus, iphase:chopi, add: 0.01)])])")
fx.save()


fx = FxList.new('tremolo', 'tremolo', {'tremolo': 0, 'beat_dur': 1, 'tremolomix': 1}, order=2, tag="modulation")
fx.add("osc = SelectX.ar(tremolomix, [osc, osc * SinOsc.ar( tremolo / beat_dur, mul:0.5, add:0.5)])")
fx.save()

fx = FxList.new('echo', 'combDelay', {'echo': 0, 'echomix' : 0.5, 'beat_dur': 1, 'echotime': 1}, order=2, tag="time")
fx.add('osc = SelectX.ar(echomix, [osc, osc + CombL.ar(osc, delaytime: echo * beat_dur, maxdelaytime: 2 * beat_dur, decaytime: echotime * beat_dur)])')
fx.save()

# Echo Boy - Roland-style delay with tape emulation
fx = FxList.new('eb', 'echoBoy', {'eb': 0.5, 'ebfeed': 0.5, 'ebmix': 0.3, 'ebmode': 0, 'ebwow': 0.1, 'ebflutter': 0.15, 'ebsat': 0.3, 'sus': 1}, order=2, tag="time")
fx.doc("Echo Boy - Roland-style delay (ebmode: 0=Digital, 1=Analog, 2=Tape)")
fx.add_var("delayed")
fx.add_var("feedback")
fx.add_var("delaytime")
fx.add_var("modulation")
fx.add_var("wowSig")
fx.add_var("flutterSig")
fx.add_var("leftDelay")
fx.add_var("rightDelay")
fx.add_var("filtered")
fx.add_var("saturated")
fx.add_var("ebhpf")
fx.add_var("eblpf")
fx.add_var("ebstereo")
fx.add("ebhpf = 100")
fx.add("eblpf = 8000")
fx.add("ebstereo = 0.5")
fx.add("delaytime = (eb * sus)")
fx.add("wowSig = SinOsc.kr(0.5 + (0.3 * LFNoise1.kr(0.2)), 0, ebwow * 0.003)")
fx.add("flutterSig = LFNoise1.kr(10 + (20 * LFNoise1.kr(0.5)), ebflutter * 0.002)")
fx.add("modulation = 1 + wowSig + flutterSig")
fx.add("leftDelay = DelayL.ar(LocalIn.ar(1) + osc[0], maxdelaytime: 2*sus, delaytime: (delaytime * modulation))")
fx.add("rightDelay = DelayL.ar(LocalIn.ar(1) + osc[1], maxdelaytime: 2*sus, delaytime: (delaytime * modulation * (1 + (ebstereo * 0.1))))")
fx.add("delayed = [leftDelay, rightDelay]")
fx.add("filtered = HPF.ar(delayed, ebhpf.clip(20, 10000))")
fx.add("filtered = LPF.ar(filtered, eblpf.clip(100, 18000))")
fx.add("saturated = Select.ar(ebmode.clip(0, 2), [filtered, (filtered * (1 + (ebsat * 2))).tanh * 0.7, (filtered * (1 + (ebsat * 4))).distort * 0.5])")
fx.add("feedback = saturated * ebfeed.clip(0, 0.95)")
fx.add("feedback = LeakDC.ar(feedback)")
fx.add("LocalOut.ar(feedback)")
fx.add("osc = (osc * (1 - ebmix)) + (saturated * ebmix)")
fx.add("osc = HPF.ar(osc, 40)")
fx.save()

fx = FxList.new('pong', 'pingpong', {'pong': 0, 'beat_dur': 1, 'pongtime': 1}, order=2, tag="time")
fx.add_var("left")
fx.add_var("right")
fx.add("left = CombN.ar(osc, delaytime: pong * beat_dur, maxdelaytime: 2 * beat_dur, decaytime: pongtime * beat_dur)")
fx.add("left = left*2.distort.tanh")
fx.add("left = LPF.ar(left,12000)")
fx.add("left = HPF.ar(left,300)")
fx.add("right = CombN.ar(osc, delaytime: pong * beat_dur + pong * beat_dur*0.5, maxdelaytime: 2 * beat_dur, decaytime: pongtime * beat_dur)")
fx.add("right = right*2.distort.tanh")
fx.add("right = LPF.ar(right,12000)")
fx.add("right = HPF.ar(right,300)")
fx.add("osc= osc + [left, right]")
fx.save()


fx = FxList.new('flanger', 'flanger', {'flanger': 0, 'fdecay': 0, 'flangermix':0.5}, order=2, tag="time")
fx.add("osc = SelectX.ar(flangermix, [osc, CombC.ar(osc, 0.01, SinOsc.ar(flanger, 0, (0.01 * 0.5) - 0.001, (0.01 * 0.5) + 0.001), fdecay, 1)])")
fx.save()

fx = FxList.new("formant", "formantFilter", {"formant": 0, 'formantmix': 0.5}, order=2, tag="filter")
fx.add("formant = (formant % 8) + 1")
fx.add("osc = SelectX.ar(formantmix, [osc, Formlet.ar(osc, formant * 200, ((formant % 5 + 1)) / 1000, (formant * 1.5) / 600).tanh])")
fx.save()

fx = FxList.new("shape", "wavesShapeDistortion", {"shape":0, "shapemix":0.5}, order=2, tag="distortion")
fx.add("osc = SelectX.ar(shapemix, [osc, (osc * (shape * 50)).fold2(1).distort / 5])")
fx.save()

fx = FxList.new("drive", "overdriveDistortion", {"drive":0, "drivemix":0.5}, order=2, tag="distortion")
fx.add("osc = SelectX.ar(drivemix, [osc, (osc * (drive * 50)).clip(0,0.2).fold2(2)])")
fx.add("osc = HPF.ar(osc, 40)")
fx.save()

fx = FxList.new("tanh", "tanhDisto", {"tanh":0, "tanhmix":0.5}, order=2, tag="distortion")
fx.add("osc = SelectX.ar(tanhmix, [osc, osc + (osc*tanh).tanh.sqrt()])")
fx.save()

fx = FxList.new("dist2", "dist2", {"dist2":0, "dist2mix": 1, "dist2shape": 0.1}, order=2, tag="distortion")
fx.add_var("tmp")
fx.add("tmp = Fold.ar(osc, -1*dist2shape,dist2shape)")
fx.add("tmp = (tmp * 16.dbamp * dist2).tanh")
fx.add("tmp = BHiShelf.ar(tmp, 9000, 0.8, -12)")
fx.add("tmp = LPF.ar(tmp, 9000)")
fx.add("osc = SelectX.ar(dist2mix, [osc, tmp])")
fx.add("osc = HPF.ar(osc, 30)")
fx.save()


fx = FxList.new("fdist", "fdist", {"fdist":0, "fdistfreq":1600}, order=2, tag="distortion")
fx.add("osc = LPF.ar(osc, fdistfreq)")
fx.add("osc = (osc * 1.1 * fdist).tanh")
fx.add("osc = LPF.ar(osc, fdistfreq)")
fx.add("osc = (osc * 1.1 * fdist).tanh")
fx.add("osc = LPF.ar(osc, fdistfreq)")
fx.add("osc = (osc * 1.4 * fdist).tanh")
fx.add("osc = LPF.ar(osc, fdistfreq)")
fx.add("osc = (osc * 2 * fdist).tanh")
fx.add("osc = osc*0.2")
fx.save()

fx = FxList.new("fdistc", "fdistc", {"fdistc":0, "fdistcfreq1":1600,"fdistcfreq2":1600,"fdistcfreq3":1600,"fdistcfreq4":1600, "fdistcm1": 1.1, "fdistcm2": 1.1, "fdistcm3": 1.4, "fdistcm4": 2, "fdistcq1": 1, "fdistcq2": 1, "fdistcq3":1, "fdistcq4":1}, order=2, tag="distortion")
fx.add("osc = RLPF.ar(osc, fdistcfreq1, fdistcq1)")
fx.add("osc = (osc * fdistcm1 * fdistc).tanh")
fx.add("osc = RLPF.ar(osc, fdistcfreq2, fdistcq2)")
fx.add("osc = (osc * fdistcm2 * fdistc).tanh")
fx.add("osc = RLPF.ar(osc, fdistcfreq3, fdistcq3)")
fx.add("osc = (osc * fdistcm3 * fdistc).tanh")
fx.add("osc = RLPF.ar(osc, fdistcfreq4, fdistcq4)")
fx.add("osc = (osc * fdistcm4 * fdistc).tanh")
fx.save()

#based on Derek Kwan chorus
fx = FxList.new("chorus", "chorus", {"chorus":0, "chorusrate":0.5}, order=2, tag="time")
fx.add_var("lfos")
fx.add_var("numDelays = 4")
fx.add_var("chrate")
fx.add_var("maxDelayTime")
fx.add_var("minDelayTime")
fx.add("chrate = Select.kr(chorusrate > 0.5, [LinExp.kr(chorusrate, 0.0, 0.5, 0.025, 0.125),LinExp.kr(chorusrate, 0.5, 1.0, 0.125, 2)])")
fx.add("maxDelayTime = LinLin.kr(chorus, 0.0, 1.0, 0.016, 0.052)")
fx.add("minDelayTime = LinLin.kr(chorus, 0.0, 1.0, 0.012, 0.022)")
fx.add("osc = osc * numDelays.reciprocal")
fx.add("lfos = Array.fill(numDelays, {|i| LFPar.kr(chrate * {rrand(0.95, 1.05)},0.9 * i,(maxDelayTime - minDelayTime) * 0.5,(maxDelayTime + minDelayTime) * 0.5,)})")
fx.add("osc = DelayC.ar(osc, (maxDelayTime * 2), lfos).sum")
fx.add("osc = Splay.ar(osc*3)")
fx.save()

# Juno-style Chorus with stereo preservation
fx = FxList.new("chorus2", "chorus2", {"chorus2":0, "chorus2rate":0.5, "chorus2depth":1, "chorus2mode":1}, order=2, tag="time")
fx.add_var("dry")
fx.add_var("wet")
fx.add_var("wetL")
fx.add_var("wetR")
fx.add_var("lfo1")
fx.add_var("lfo2")
fx.add_var("lfo3")
fx.add_var("rate")
fx.add_var("depth")
fx.add_var("baseDelay")

# Store dry signal
fx.add("dry = osc")

# Map rate and depth similar to Juno's sweet spots
fx.add("rate = LinExp.kr(chorus2rate, 0.0, 1.0, 0.2, 1.2)")
fx.add("depth = LinLin.kr(chorus2depth, 0.0, 1.0, 0.001, 0.004)")
fx.add("baseDelay = 0.003")

# Three BBD-style LFOs with phase offsets (like Juno's BBD chips)
fx.add("lfo1 = SinOsc.kr(rate * 0.51, 0, depth, baseDelay)")
fx.add("lfo2 = SinOsc.kr(rate * 0.73, 1.2, depth * 0.9, baseDelay)")
fx.add("lfo3 = SinOsc.kr(rate * 1.19, 2.4, depth * 0.8, baseDelay)")

# Mode 1: Single chorus - both channels use same LFO
fx.add("wetL = Select.kr(chorus2mode.clip(1,3) - 1, [DelayC.ar(osc[0], 0.02, lfo1), DelayC.ar(osc[0], 0.02, lfo1) + DelayC.ar(osc[0], 0.02, lfo2), DelayC.ar(osc[0], 0.02, lfo1) + DelayC.ar(osc[0], 0.02, lfo2) + DelayC.ar(osc[0], 0.02, lfo3)])")
fx.add("wetR = Select.kr(chorus2mode.clip(1,3) - 1, [DelayC.ar(osc[1], 0.02, lfo1), DelayC.ar(osc[1], 0.02, lfo2) + DelayC.ar(osc[1], 0.02, lfo3), DelayC.ar(osc[1], 0.02, lfo2) + DelayC.ar(osc[1], 0.02, lfo3) + DelayC.ar(osc[1], 0.02, lfo1)])")
fx.add("wet = [wetL, wetR]")

# Gentle HPF to remove DC offset and low rumble (like analog chorus)
fx.add("wet = HPF.kr(wet, 30)")

# Mix with dry signal - Juno has fixed 50/50 mix but we make it controllable
fx.add("osc = SelectX.ar(chorus2, [dry, (dry * 0.7) + (wet * 0.6)])")
fx.save()

# dub delay based on «Dub Echo» by Bjorn Westergard [sccode https://sccode.org/1-h]
fx = FxList.new('dubd', 'dubdelay', {'dubd': 0, 'dublen': 0.1, 'dubwidth': 0.12, 'dubfeed': 0.8}, order=2, tag="time")
fx.add_var("dry")
fx.add("dry = osc")
fx.add("osc = osc + Fb({ |feedback| var left, right; var magic = LeakDC.ar(feedback*dubfeed + osc); magic = HPF.ar(magic, 400); magic = LPF.ar(magic, 5000); magic = magic.tanh; #left, right = magic; magic = [DelayC.ar(left, 1, LFNoise2.ar(12).range(0,dubwidth)), DelayC.ar(right, 1, LFNoise2.ar(12).range(dubwidth,0))].reverse;	},dublen)")
fx.add("osc = SelectX.ar(dubd, [dry, osc])")
fx.save()

fx = FxList.new('octafuz', 'octafuz', {'octafuz': 0, 'octamix': 0.5}, order=2, tag="distortion")
fx.add_var("dis")
fx.add_var("osc_base")
fx.add("osc_base = osc")
fx.add("dis = [1,1.01,2,2.02,4.5,6.01,7.501]")
fx.add("dis = dis ++ (dis*6)")
fx.add("osc = ((osc * dis*octafuz).sum.distort)")
fx.add("osc = (osc * 1/6)!2")
fx.add("osc = SelectX.ar(octamix, [osc_base, osc])")
fx.save()

fx = FxList.new('tek', 'tek', {'tek': 0, 'tekr':500, 'tekd':8}, order=2, tag="distortion")
fx.add_var("osc_low")
fx.add_var("osc_med")
fx.add_var("osc_high")
fx.add_var("osc_base")
fx.add_var("lfo")
fx.add("lfo = SinOsc.ar(0.5, phase: 0, mul: 50, add: 800)")
fx.add("osc = In.ar(bus, 2)")
fx.add("osc_base = osc")
fx.add("osc_low = LPF.ar(osc, lfo) * 1")
fx.add("osc_med = BPF.ar(osc, lfo * 2)")
fx.add("osc_med = osc_med + Ringz.ar(CrossoverDistortion.ar(osc_med, 1, 0.1, 0.4),100, decaytime: 0.15, mul:0.1)")
fx.add("osc_med = LeakDC.ar(osc_med)")
fx.add("osc_high = HPF.ar(osc, 4000 + SinOsc.ar(4, mul: 24))")
fx.add("osc = osc_low + osc_med + osc_high")
fx.add("osc = DFM1.ar(osc, [400, 600], 0.99, tekd, 0) + osc")
fx.add("osc = RHPF.ar(Gammatone.ar(osc, tekr), tekr, mul:2) + osc")
fx.add("osc = SelectX.ar(tek, [osc_base, osc])")
fx.save()


fx = FxList.new('crush2', 'crush2', {'crush2': 0, 'bits2': 8, 'crush2mix': 0.5}, order=2, tag="distortion")
fx.add_var("trig")
fx.add("trig = Impulse.ar(SampleRate.ir/bits2)")
fx.add("osc = osc.round(2.pow(crush2).reciprocal)")
fx.add("osc = SelectX.ar(crush2mix, [osc, Latch.ar(osc, trig)])")
fx.save()

### TIDAL FX ####
fx = FxList.new("krush", "dirt_krush", {"krush":0, "kutoff":15000, "krushmix": 0.5}, order=2, tag="distortion")
fx.add_var("signal")
fx.add_var("freq")
fx.add("freq = Select.kr(kutoff > 0, [DC.kr(4000), kutoff])")
fx.add("signal = (osc.squared + (krush * osc)) / (osc.squared + (osc.abs * (krush-1.0)) + 1.0)")
fx.add("signal = RLPF.ar(signal, clip(freq, 20, 10000), 1)")
fx.add("osc = SelectX.ar(krushmix, [osc, signal])")
fx.save()

fx = FxList.new("drop", "waveloss", {"drop":0, "dropof": 100}, order=2, tag="distortion")
fx.add("osc = WaveLoss.ar(osc, drop, outof: dropof, mode: 2)")
fx.save()

fx = FxList.new("squiz", "squiz", {"squiz":0}, order=2, tag="distortion")
fx.add("osc = Squiz.ar(osc, squiz)")
fx.save()

fx = FxList.new("triode", "triode", {"triode":0}, order=2, tag="distortion")
fx.add_var("sc")
fx.add("sc = triode * 10 + 1e-3")
fx.add("osc = (osc * (osc > 0)) + (tanh(osc * sc) / sc * (osc < 0))")
fx.add("osc = LeakDC.ar(osc)*1.2")
fx.save()

#### Need Tweak ##############
fx = FxList.new("octer", "octer", {"octer":0, "octersub": 0, "octersubsub": 0}, order=1, tag="pitch")
fx.add_var("oct1")
fx.add_var("oct2")
fx.add_var("oct3")
fx.add_var("sub")
fx.add("oct1 = 2.0 * LeakDC.ar(abs(osc))")
fx.add("sub = LPF.ar(osc, 440)")
fx.add("oct2 = ToggleFF.ar(sub)")
fx.add("oct3 = ToggleFF.ar(oct2)")
fx.add("osc = SelectX.ar(octer, [osc, octer*oct1, DC.ar(0)])")
fx.add("osc = osc + (octersub * oct2 * sub) + (octersubsub * oct3 * sub)")
fx.save()

fx = FxList.new("feed", "feeddelay", {"feed":0.7, "feedfreq": 50}, order=2,tag="time")
fx.add_var("out")
fx.add("out = osc + Fb({\
		arg feedback;\
		osc = CombN.ar(HPF.ar(feedback*feed, feedfreq) + osc, 0.5, 0.25).tanh;\
	},0.5,0.125)")
fx.save()

fx = FxList.new("a", "attack", {"a":0, "sus": 1, "ac": 0}, order=2, tag="envelope")
fx.doc("attack envelope")
fx.add_var("env")
fx.add("env = EnvGen.ar(Env.new(levels: [0,1,1], times:[a*sus, sus - a*sus], curve:[ac,0]))")
fx.add("osc = osc*env")
fx.save()

fx = FxList.new("r", "releas", {"r":0, "sus": 1, "rc": 0}, order=2, tag="envelope")
fx.doc("release envelope")
fx.add_var("env")
fx.add("env = EnvGen.ar(Env.new(levels: [1,0,0], times:[r*sus, sus - r*sus], curve:[rc,0]))")
fx.add("osc = osc*env")
fx.save()

fx = FxList.new('ehpf','envHPF', {'ehpf': 0, 'ehpr': 0.7, 'ehpa':0.001, 'ehps':0.01, 'ehpc':-3, 'sus':1}, order=2, tag="filter")
fx.doc("ehpf")
fx.add_var("env")
fx.add('env = EnvGen.ar(Env.new([0, 1, 1, 0.1], [ehpa*sus, sus-(ehpa*sus)-(ehps*sus), ehps], ehpc))')
fx.add('osc = RHPF.ar(osc, ehpf, ehpr, mul: env)')
fx.save()

fx = FxList.new('elpf','envLPF', {'elpf': 0, 'elpr': 0.7, 'elpa':0.001, 'elps':0.01, 'elpc':-3, 'sus':1}, order=2, tag="filter")
fx.doc("elpf")
fx.add_var("env")
fx.add('env = EnvGen.ar(Env.new([0.01, 1, 1, 0.01], [elpa*sus, sus-(elpa*sus)-(elps*sus), elps], elpc), doneAction:0)')
fx.add('osc = RLPF.ar(osc, LinLin.ar(env, 0,1,0,elpf)+10, elpr, mul: 1)')
fx.save()

fx = FxList.new("position", "trimPos", {"position": 0, "sus": 1}, order=2, tag="envelope")
fx.add("osc = osc * EnvGen.ar(Env(levels: [0,0,1], curve: 'step', times: [sus * position, 0]))")
fx.save()

fx = FxList.new("ring", "ring_modulation", {"ring":0, "ringl":500, "ringh":1500}, order=0, tag="modulation")
fx.add_var("mod")
fx.add("mod = ring * SinOsc.ar(Clip.kr(XLine.kr(ringl, ringl + ringh), 20, 20000))")
fx.add("osc = ring1(osc, mod)")
fx.save()

fx = FxList.new("shift", "pitchshifter", {"shift":0, "shiftsize": 0.1}, order=1, tag="pitch")
fx.add("osc = PitchShift.ar(osc, shiftsize, shift, 0.02, 0.01)")
fx.save()


fx = FxList.new("comp", "comp", {"comp": 0, "comp_down": 1, "comp_up": 0.8}, order=2, tag="volume")
fx.add("osc = Compander.ar(osc, osc, thresh: comp, slopeAbove: comp_down, slopeBelow: comp_up, clampTime: 0.01, relaxTime: 0.01, mul: 1)")
fx.save()

fx = FxList.new("drcomp", "drcomp", {"drcomp": 0, }, order=2, tag="volume")
fx.add_var("compOsc")
fx.add("compOsc = Compander.ar(osc, osc, thresh: 0.1, slopeBelow:1, slopeAbove: 0.1, clampTime: 0.002, relaxTime: 0.05, mul:3)")
fx.add("compOsc = BLowShelf.ar(compOsc, 200, 1, 2, 1)")
fx.add("compOsc = BHiShelf.ar(compOsc, 6000, 1, 3)")
fx.add("osc = SelectX.ar(drcomp, [osc, compOsc*0.7])")
fx.save()

fx = FxList.new("mu", "mimu", {"mu": 0}, order=2,tag="volume")
fx.add("osc = MiMu.ar(osc, mu)")
fx.save()


fx = FxList.new("sidechain", "sidechain", {"sidechain": 0, "sidechain_atk": 0.05, "sidechain_rel": 0.1, "thresh":0.006}, order=2, tag="volume")
fx.add_var("schain")
fx.add("schain = In.ar(sidechain,1)")
fx.add("osc = Compander.ar(osc, schain, thresh: thresh, slopeAbove: 0.1, slopeBelow: 1, clampTime: sidechain_atk, relaxTime: sidechain_rel, mul: 1)")
fx.save()

fx = FxList.new("lofi", "lofi", {"lofi": 0, "lofiwow": 0.5, "lofiamp":0.5}, order=2, tag="filter")
fx.add_var("minWowRate")
fx.add_var("wowRate")
fx.add_var("maxDepth")
fx.add_var("maxLfoDepth")
fx.add_var("depth")
fx.add_var("depthLfoAmount")
fx.add_var("wowMul")
fx.add_var("maxDelay")
fx.add_var("ratio")
fx.add_var("threshold")
fx.add_var("gain")
fx.add("osc = HPF.ar(osc, 25)")
fx.add("ratio = LinExp.kr(lofiamp, 0, 1, 0.15, 0.01)")
fx.add("threshold = LinLin.kr(lofiamp, 0, 1, 0.8, 0.33)")
fx.add("gain = 1/(((1.0-threshold) * ratio) + threshold)")
fx.add("osc = Limiter.ar(Compander.ar(osc, osc, threshold, 1.0, ratio, 0.1, 1, gain), dur: 0.0008)")
fx.add("minWowRate = 0.5")
fx.add("wowRate = LinExp.kr(lofiwow, 0, 1, minWowRate, 4)")
fx.add("maxDepth = 35")
fx.add("maxLfoDepth = 5")
fx.add("depth = LinExp.kr(lofiwow, 0, 1, 1, maxDepth - maxLfoDepth)")
fx.add("depthLfoAmount = LinLin.kr(lofiwow, 0, 1, 1, maxLfoDepth).floor")
fx.add("depth = LFPar.kr(depthLfoAmount * 0.1, mul: depthLfoAmount, add: depth)")
fx.add("wowMul = ((2 ** (depth * 1200.reciprocal)) - 1)/(4 * wowRate)")
fx.add("maxDelay = (((2 ** (maxDepth * 1200.reciprocal)) - 1)/(4 * minWowRate)) * 2.5")
fx.add("osc = DelayC.ar(osc, maxDelay, SinOsc.ar(wowRate, 2, wowMul, wowMul + ControlRate.ir.reciprocal))")
fx.add("osc = ((osc * LinExp.kr(lofiamp, 0, 1, 1, 2.5))).tanh")
fx.add("osc = LPF.ar(osc, LinExp.kr(lofi, 0, 1, 2500, 10000))")
fx.add("osc = HPF.ar(osc, LinExp.kr(lofi, 0, 1, 40, 1690))")
fx.add("osc = MoogFF.ar(osc, LinExp.kr(lofi, 0, 1, 1000, 10000), 0)")
fx.save()

### need the miSCellaneous Quark, install in SC
fx = FxList.new("fold", "wavefold", {"fold": 0, "symetry": 1, "smooth": 0.5}, order=2, tag="distortion")
fx.add_var("gain")
fx.add_var("compensationGain")
fx.add_var("envFollower")
fx.add_var("ampgain")
fx.add("compensationGain = max(LinLin.kr(fold, 0, 1, 1, 20) * 0.75, 1).reciprocal")
fx.add("envFollower = EnvFollow.ar((osc * 2).softclip, 0.9999)")
fx.add("ampgain = (compensationGain * (1 - 0.4)) + (envFollower * 0.4)")
fx.add("osc = SmoothFoldS.ar((osc + LinLin.kr(symetry, 0, 1, 1, 0)) * LinLin.kr(fold, 0, 1, 1, 20), smoothAmount: smooth)")
fx.add("osc = LeakDC.ar(osc*ampgain)")
fx.save()

fx = FxList.new('low','L_Equalizer', { 'low': 1, 'lowfreq': 80}, order=2, tag="filter")
fx.doc("Low shelf Equalizer")
fx.add('osc = BLowShelf.ar(osc, freq: lowfreq, db: abs(low).ampdb)')
fx.save()

fx = FxList.new('mid','M_Equalizer', {'mid': 1, 'midfreq': 1000, 'midq': 1}, order=2, tag="filter")
fx.doc("Middle boost Equalizer")
fx.add('osc = BPeakEQ.ar(osc, freq: midfreq, rq: midq.reciprocal, db: abs(mid).ampdb)')
fx.save()

fx = FxList.new('high','H_Equalizer', {'high': 1, 'highfreq': 8000}, order=2, tag="filter")
fx.doc("High shelf Equalizer")
fx.add('osc = BHiShelf.ar(osc, freq: highfreq, db: abs(high).ampdb)')
fx.save()

fx = FxList.new('bell','Bell_Filter', {'bell': 0.5, 'bellf': 3000, 'bellq': 0.9}, order=2, tag="filter")
fx.doc("Bell Filter")
fx.add('osc = NonlinearFilter.ar(osc, freq: bellf, shape:0, gain:bell, q:bellq, saturation: 1)')
fx.save()


fx = FxList.new('djf','djFilter', {'djf': 0, 'djfq': 0.3}, order=2,tag="filter")
fx.doc("DJ Filter")
fx.add_var('lpfCutoffFreq')
fx.add_var('hpfCutoffFreq')
fx.add('lpfCutoffFreq = djf.linexp(0, 0.5, 50, 15000)')
fx.add('hpfCutoffFreq = djf.linexp(0.5, 1, 50, 15000)')
fx.add('osc = RHPF.ar(RLPF.ar(osc,lpfCutoffFreq, djfq),hpfCutoffFreq, djfq)')
fx.save()

fx = FxList.new('phaser', 'phaser', {'phaser': 0, 'phaserdepth': 0.5}, order=2,tag="modulation")
fx.add_var("delayedSignal")
fx.add("delayedSignal = osc")
fx.add("for(1, 4, {|i| delayedSignal = AllpassL.ar(delayedSignal, 0.01 * 4.reciprocal, LFPar.kr(LinExp.kr(phaser, 0, 1, 0.275, 16), i + 0.5.rand, LinExp.kr(phaserdepth*4.reciprocal, 0, 1, 0.0005, 0.01 * 0.5), LinExp.kr(phaserdepth*4.reciprocal, 0, 1, 0.0005, 0.01 * 0.5)), 0)})")
fx.add("osc = osc + delayedSignal")
fx.save()

fx = FxList.new('ringz','Ringmod', {'ringzfreq': 50, 'ringz': 0.1}, order=2, tag="modulation")
fx.doc("Ringmodulation")
fx.add('osc = Ringz.ar(osc, freq: ringzfreq, decaytime: ringz, mul: 0.05)')
fx.save()

fx = FxList.new('resonz','resonz', {'rfreq': 50, 'resonz': 0.1}, order=2, tag="filter")
fx.doc("Resonz")
fx.add('osc = Resonz.ar(osc, freq: rfreq, bwr: resonz)')
fx.save()

fx = FxList.new('room2', 'reverb_stereo', {'room2': 0, 'mix2': 0.2, 'damp2':0.8, 'revatk':0, 'revsus':1}, order=2, tag="reverb")
fx.add_var("dry")
fx.add("dry = osc")
fx.add("osc = HPF.ar(osc, 100)")
fx.add("osc = LPF.ar(osc, 10000)")
fx.add("osc = FreeVerb2.ar(osc[0], osc[1], 1, room2, damp2)")
fx.add("osc = osc * EnvGen.ar(Env([0,1,0], [revatk,revsus], curve: 'welch'))")
fx.add("osc = SelectX.ar(mix2, [dry, osc])")
fx.save()

fx = FxList.new('mverb', 'miVerb', {'mverb': 0, 'mverbmix': 0.5, 'mverbdamp':0.8, 'mverbdiff':0.625, 'mverbfreeze': 0}, order=2, tag="reverb")
fx.add("osc = MiVerb.ar(osc, time: mverb.clip(0.0,1.0), drywet: mverbmix, damp: mverbdamp, hp: 0.1, freeze: mverbfreeze, diff: mverbdiff, mul:1.5)")
fx.save()

fx = FxList.new('jpverb', 'jpVerb', {'jpverb': 0, 'jpmix': 0.5, 'jpdamp':0.0, 'jpsize': 1.0}, order=2, tag="reverb")
fx.add_var("dry")
fx.add("dry = osc")
fx.add("osc = JPverb.ar(osc, t60: jpverb, damp: jpdamp, size: jpsize)")
fx.add("osc = SelectX.ar(jpmix, [dry, osc])")
fx.save()

fx = FxList.new('stut', 'stutterfx', { 'stut': 1, 'stutrate':1, 'stutlen':0.02, 't_reset': 0}, order=2, tag="modulation")
fx.add_var("dry")
fx.add_var("reset")
fx.add_var("wet")
fx.add("~stutter = { |snd, reset, stutlen, maxdelay = 1| var phase, fragment, del; phase = Sweep.ar(reset); fragment = { |ph| (ph - Delay1.ar(ph)) < 0 + Impulse.ar(0) }.value(phase / stutlen % 1); del = Latch.ar(phase, fragment) + ((stutlen - Sweep.ar(fragment)) * (stutrate - 1)); DelayC.ar(snd, maxdelay, del); }")
fx.add("dry = osc")
fx.add("reset = Onsets.kr(FFT(LocalBuf(1024), osc), t_reset)")
fx.add("wet = ~stutter.(osc, reset, stutlen)")
fx.add("osc = SelectX.ar(stut, [dry, wet], wrap:1)")
fx.save()

fx = FxList.new('sbrk', 'stutbreak', {'sbrk': 0.5, 't_reset': 0, 'sbrkdur': 0.5, 'sbrkmix': 1.0, 'sus': 1}, order=2, tag="modulation")
fx.add_var("dry")
fx.add_var("reset")
fx.add_var("wet")
fx.add_var("stuti")
fx.add_var("stutlen")
fx.add_var("stutrate")
fx.add_var("drystut")
fx.add("stutrate=Rand(0.01, 1.0)")
fx.add("stutlen=Rand(0.01,0.08)")
fx.add("~stutter = { |snd, reset, stutlen, maxdelay = 1| var phase, fragment, del; phase = Sweep.ar(reset); fragment = { |ph| (ph - Delay1.ar(ph)) < 0 + Impulse.ar(0) }.value(phase / stutlen % 1); del = Latch.ar(phase, fragment) + ((stutlen - Sweep.ar(fragment)) * (stutrate - 1)); DelayC.ar(snd, maxdelay, del); }")
fx.add("dry = osc")
fx.add("stuti = IRand(1,sus*sbrkdur).round(2)")
fx.add("reset = Onsets.kr(FFT(LocalBuf(1024), osc), t_reset)")
fx.add("wet = ~stutter.(osc, reset, stutlen)")
fx.add("wet = wet * LFPulse.kr(stuti/sus, 0.5, mul:1.0)")
fx.add("drystut = dry * LFPulse.kr(stuti/sus, mul:1.5)")
fx.add("osc = SelectX.ar(sbrk, [drystut, wet], wrap:1)")
fx.add("osc = SelectX.ar(sbrkmix, [dry, osc], wrap:1)")
fx.save()

fx = FxList.new('clouds','clouds', {'clouds': 0, 'cpos':0.5, 'csize':0.25, 'cdens': 0.4, 'ctex': 0.5, 'cpitch': 0, 'cgain':2, 'cfb': 0, 'cmode': 0}, order=2, tag="reverb")
fx.doc("Clouds granulator")
fx.add("osc = MiClouds.ar(osc, pit: cpitch, pos: cpos, size:csize, dens: cdens, tex: ctex, drywet: clouds, in_gain: cgain, fb: cfb, mode:cmode)")
fx.save()

fx = FxList.new('mring','MiRings', {'mring': 0, 'rstruct':0.1, 'rbright': 0.8, 'rdamp': 0.7, 'rpos': 0, 'rmodel': 1, 'rpoly': 4, 'regg': 0, 'sus':0, 'rsus': 2}, order=2, tag="modulation")
fx.doc("Mi Rings resonator")
fx.add_var("dry")
fx.add_var("pitch")
fx.add("pitch = In.kr(bus, 1)")
fx.add("dry = osc")
fx.add("osc = MiRings.ar(in: osc,trig:1,pit: pitch.cpsmidi.clip(1,80),struct: rstruct, bright: rbright, damp: rdamp, pos: rpos, model: rmodel, poly: rpoly, intern_exciter: 1, easteregg: regg, mul: 1)")
fx.add("osc = osc * EnvGen.kr(Env([1,1,0], [sus*rsus, 0.01]), doneAction: 2)")
fx.add("osc = SelectX.ar(mring, [dry, osc], wrap:1)")
fx.save()

fx = FxList.new('blow','MiBlow', {'blow': 0, 'bflow': 0.3, 'bmodel': 0, 'bpos': 0.2, 'sus':0}, order=1, tag="pitch")
fx.doc("Mi Blow resonator")
fx.add_var("dry")
fx.add_var("pitch")
fx.add("pitch = In.kr(bus, 1)")
fx.add("dry = osc")
fx.add("osc = MiElements.ar(osc, 0, 1, pitch.cpsmidi.clip(1,70), blow_level:1, space:0.8, contour: 0.8, flow: bflow, damp:0.7, model:bmodel, pos:bpos)")
fx.add("osc = osc * EnvGen.kr(Env([1,1,0], [sus, 0.5]), doneAction: 2)")
fx.add("osc = LPF.ar(osc, 18000)")
fx.add("osc = Splay.ar(osc)")
fx.add("osc = SelectX.ar(blow, [dry, osc*0.5], wrap:1)")
fx.save()


fx = FxList.new('panR','panR', {'panR': 1}, order=2, tag="panning")
fx.doc("Pan rear")
fx.add("osc = Pan4.ar(osc, 0, panR)")
fx.save()


fx = FxList.new('vol','volume', {'vol': 1}, order=2, tag="volume")
fx.doc("Volume")
fx.add("osc = osc*vol")
fx.save()


# Fx LOOP
fx = FxList.new('fx1','fx1out', {'fx1': 0, 'lpfx1':22000, 'hpfx1':0, 'fx1mix': 1}, order=2, tag="util")
fx.doc("FX1 Bus")
fx.add_var("fxsig")
fx.add("fxsig = LPF.ar(osc, lpfx1)")
fx.add("fxsig = HPF.ar(fxsig, hpfx1)")
fx.add("Out.ar(4, Mix.ar(fxsig*fx1))")
fx.add("osc = osc * fx1mix")
fx.save()

fx = FxList.new('fx2','fx2out', {'fx2': 0, 'lpfx2':22000, 'hpfx2':0, 'fx2mix': 1}, order=2, tag="util")
fx.doc("FX2 Bus")
fx.add_var("fxsig")
fx.add("fxsig = LPF.ar(osc, lpfx2)")
fx.add("fxsig = HPF.ar(fxsig, hpfx2)")
fx.add("Out.ar(5, Mix.ar(fxsig*fx2))")
fx.add("osc = osc * fx2mix")
fx.save()

fx = FxList.new('fx','fxout', {'fx': 0, 'lpfx':22000, 'hpfx':0, "fxout": 2, "fxmix": 1}, order=2, tag="util")
fx.doc("FX Bus")
fx.add_var("fxsig")
fx.add("fxsig = LPF.ar(osc, lpfx)")
fx.add("fxsig = HPF.ar(fxsig, hpfx)")
fx.add("Out.ar([fxout, fxout+1], Mix.ar(fxsig*fx))")
fx.add("osc = osc * 0")
fx.save()

fx = FxList.new('output','output', {'output': 0}, order=2, tag="util")
fx.doc("Output select Bus")
fx.add("Out.ar(output, osc)")
fx.save()

fx = FxList.new('mon','monitoring', {'mon': 0}, order=2, tag="util")
fx.doc("Monitoring Bus")
fx.add("Out.ar([mon, mon+1], osc)")
fx.add("osc = osc*0")
fx.save()


fx = FxList.new("wshape", "waveshaper", {"wshape": 0, "wgain": 1, "wmix": 0.5}, order=2, tag="distortion")
fx.doc("Waveshaper distortion whith different waveforms")
fx.add_var("shaped")
fx.add_var("input_signal")
fx.add_var("x")
fx.add_var("wt")
fx.add_var("wt0")
fx.add_var("wt1")
fx.add_var("wt2")
fx.add_var("wt3")
fx.add_var("wt4")
fx.add_var("wt5")
fx.add_var("wt6")
fx.add_var("wt7")
fx.add_var("wt8")
fx.add_var("wt9")
fx.add_var("wt10")
fx.add_var("wt11")
fx.add("input_signal = (osc * wgain).clip(-1, 1)")
fx.add("x = input_signal")
fx.add("wt= x")
fx.add("wt0 = x + ((x * 8).sin * 0.4 * exp(-3 * x.abs))")
fx.add("wt1 = (x.tanh + (x ** 3 * 0.2 * (1 - x.abs)) + ((x * 3).sin * 0.05))*1.5")
fx.add("wt2 = ((x * 4).fold(-1, 1) * 1.3 + (x * 1.7))*0.4")
fx.add("wt3 = (x.sign * (sin(x.abs * pi * 2) * x.abs * 2))*1.5")
fx.add("wt4 = (x.sign * (x.abs ** (0.5 + x.abs)) * (1 - x.abs ** 2))*1.5")
fx.add("wt5 = (x.sign * ((x.abs ** 0.4) * (1 - (x.abs ** 0.6))) + (x * 0.1))*1.3")
fx.add("wt6 = (x.sign * (x.abs ** (1 + x.abs * 0.4)) * (1 - (x.abs * 0.1)))")
fx.add("wt7 = x.sign * (x.abs ** 0.2)")
fx.add("wt8 = ((x * 3).wrap(-0.5, 0.5) * 2.5 + (x * 0.3))*0.4")
fx.add("wt9 = (x.sign * ((x.abs ** 0.2) - (x.abs ** 2.5)))*0.5")
fx.add("wt10 = (x.sign * (x.abs ** (3 - 2.5 * x.abs)))*0.4")
fx.add("wt11 = (((x % 0.3) * 5) - 0.75)*1.2")
fx.add("shaped = Select.ar(wshape, [wt, wt0, wt1, wt2, wt3, wt4, wt5, wt6, wt7, wt8, wt9, wt10, wt11])")
fx.add("shaped = HPF.ar(shaped, 20)")
fx.add("shaped = LeakDC.ar(shaped*0.4)")
fx.add("osc = SelectX.ar(wmix, [osc, shaped])")
fx.save()

# Auto Pan
fx = FxList.new('apan', 'autopan', {'apan': 0, 'awidth': 1, 'apwave': 0, 'beat_dur': 1}, order=2, tag="panning")
fx.doc("Rhythmic auto-panning with waveform selection (0=sine, 1=tri, 2=saw, 3=pulse)")
fx.add_var("panLfo")
fx.add_var("rate")
fx.add("rate = apan / beat_dur")
fx.add("panLfo = SelectX.kr(apwave, [SinOsc.kr(rate), LFTri.kr(rate), LFSaw.kr(rate), LFPulse.kr(rate)])")
fx.add("osc = Pan2.ar(osc[0] + osc[1], panLfo * awidth)")
fx.save()

# Frequency Shifter
fx = FxList.new('fshift', 'freqshift', {'fshift': 0, 'fphase': 0, 'fmix': 0.5}, order=2, tag="pitch")
fx.doc("Frequency shifter - shifts all frequencies by a fixed Hz amount (creates metallic/robotic sounds)")
fx.add_var("dry")
fx.add_var("wet")
fx.add("dry = osc")
fx.add("wet = FreqShift.ar(osc, fshift, fphase)")
fx.add("osc = SelectX.ar(fmix, [dry, wet])")
fx.save()

# Shimmer Reverb
fx = FxList.new('shimmer', 'shimmer', {'shimmer': 0, 'shimsize': 0.8, 'shimpitch': 0.5, 'shimmix': 0.5}, order=2, tag="reverb")
fx.doc("Shimmer reverb - octave-up pitch shift + reverb for ethereal sounds")
fx.add_var("dry")
fx.add_var("pitched")
fx.add_var("reverbed")
fx.add_var("wet")
fx.add("dry = osc")
fx.add("pitched = PitchShift.ar(osc, 0.2, LinExp.kr(shimpitch, 0, 1, 1, 2), 0, 0.01)")
fx.add("reverbed = FreeVerb.ar(osc + (pitched * 0.5), shimmix, shimsize)")
fx.add("wet = reverbed * LinLin.kr(shimmer, 0, 1, 0.3, 1.5)")
fx.add("osc = SelectX.ar(shimmer, [dry, wet])")
fx.save()

###########

# === INDUSTRIAL DISTORTIONS ===

# Fuzz - asymmetric clipping, octave artifacts, rich harmonics
fx = FxList.new("fuzz", "fuzz", {"fuzz": 0.5, "fuzzgain": 2, "fuzztone": 0.5, "fuzzoctave": 0.3}, order=2, tag="distortion")
fx.doc("Asymmetric fuzz with octave-up artifacts")
fx.add_var("dry")
fx.add_var("fuzzed")
fx.add_var("octaveUp")
fx.add_var("subHarm")
fx.add("dry = osc")
fx.add("osc = LPF.ar(osc, 6000)")
fx.add("osc = Compander.ar(osc, osc, 0.2, 1, 0.6, 0.002, 0.05, 1.5)")
fx.add("fuzzed = (osc * fuzzgain * 2.5)")
fx.add("fuzzed = fuzzed + (fuzzed.cubed * 0.15)")
fx.add("fuzzed = fuzzed.clip(-0.85, 0.55)")
fx.add("octaveUp = (osc.abs * fuzzgain * 1.5).softclip * fuzzoctave")
fx.add("subHarm = LPF.ar(osc * 0.5, 200).wrap(-0.3, 0.3) * (1 - fuzztone) * 0.4")
fx.add("fuzzed = fuzzed + octaveUp + subHarm")
fx.add("fuzzed = BPeakEQ.ar(fuzzed, 800, 0.8, fuzztone * 3)")
fx.add("fuzzed = LPF.ar(fuzzed, 4000 + (fuzztone * 6000))")
fx.add("fuzzed = LeakDC.ar(fuzzed)")
fx.add("osc = XFade2.ar(dry, fuzzed * 0.7, fuzz * 2 - 1)")
fx.save()

# Tape saturation - warm compression + saturation + wobble + HF rolloff
fx = FxList.new("tape", "tape", {"tape": 0.5, "tapedrive": 1.5, "tapewarm": 0.5, "tapewobble": 0.1}, order=2, tag="distortion")
fx.doc("Tape saturation with warmth, compression and subtle wobble")
fx.add_var("dry")
fx.add_var("saturated")
fx.add_var("wobble")
fx.add("dry = osc")
fx.add("osc = Compander.ar(osc, osc, 0.25, 1, 0.4, 0.002, 0.08, 1.4)")
fx.add("wobble = SinOsc.kr(LFNoise1.kr(0.5).range(0.3, 1.5)).range(0.98, 1.02)")
fx.add("saturated = osc * tapedrive * wobble")
fx.add("saturated = saturated + (saturated.squared * tapewarm * 0.5)")
fx.add("saturated = saturated + (saturated.cubed * 0.08)")
fx.add("saturated = saturated.softclip")
fx.add("saturated = saturated + DelayC.ar(saturated * 0.15, 0.01, LFNoise2.kr(3).range(0.0001, 0.001 + (tapewobble * 0.003)))")
fx.add("saturated = LPF.ar(saturated, 10000 - (tapewarm * 4000))")
fx.add("saturated = BLowShelf.ar(saturated, 120, 0.7, tapewarm * 2.5)")
fx.add("saturated = BHiShelf.ar(saturated, 6000, 0.8, tapewarm * -2)")
fx.add("saturated = LeakDC.ar(saturated)")
fx.add("osc = XFade2.ar(dry, saturated * 0.85, tape * 2 - 1)")
fx.save()

# Envelope-controlled distortion with multiband
fx = FxList.new("envdist", "envdist", {"envdist": 0.5, "envdistgain": 2, "envdistsens": 1, "envdistattack": 0.01}, order=2, tag="distortion")
fx.doc("Distortion amount follows signal amplitude - punchy dynamics")
fx.add_var("dry")
fx.add_var("env")
fx.add_var("distAmount")
fx.add_var("distorted")
fx.add_var("lowDist")
fx.add_var("highDist")
fx.add("dry = osc")
fx.add("env = Amplitude.kr(osc, envdistattack, 0.08)")
fx.add("env = (env * envdistsens * 8).clip(0, 1)")
fx.add("distAmount = envdistgain * (0.8 + (env * 4))")
fx.add("lowDist = LPF.ar(osc, 400)")
fx.add("lowDist = (lowDist * distAmount * 0.8).softclip")
fx.add("highDist = HPF.ar(osc, 400)")
fx.add("highDist = LPF.ar(highDist, 8000)")
fx.add("highDist = (highDist * distAmount * 1.2)")
fx.add("highDist = highDist + (highDist.cubed * 0.2)")
fx.add("highDist = highDist.fold(-0.9, 0.9)")
fx.add("distorted = lowDist + (highDist * 0.7)")
fx.add("distorted = distorted + ((distorted * env * 1.5).wrap(-0.6, 0.6) * 0.25)")
fx.add("distorted = LPF.ar(distorted, 7000)")
fx.add("distorted = LeakDC.ar(distorted)")
fx.add("osc = XFade2.ar(dry, distorted * 0.75, envdist * 2 - 1)")
fx.save()

# Tube drive - warm, even harmonics, rich compression
fx = FxList.new("tube", "tubedrive", {"tube": 0.5, "tubegain": 1.5, "tubewarm": 0.6, "tubebias": 0.1}, order=2, tag="distortion")
fx.doc("Tube-style saturation with even harmonics and warmth")
fx.add_var("dry")
fx.add_var("biased")
fx.add_var("saturated")
fx.add_var("harmonics")
fx.add_var("compressed")
fx.add("dry = osc")
fx.add("osc = Compander.ar(osc, osc, 0.3, 1, 0.5, 0.001, 0.06, 1.3)")
fx.add("biased = osc + (tubebias * 0.15)")
fx.add("saturated = biased * tubegain * 1.8")
fx.add("saturated = saturated - (saturated.cubed * 0.25)")
fx.add("saturated = saturated + (saturated.squared.sign * saturated.squared.abs * 0.1)")
fx.add("harmonics = (osc.squared * tubewarm * 0.4).softclip")
fx.add("harmonics = harmonics + (osc.cubed * tubewarm * 0.15)")
fx.add("saturated = saturated + harmonics")
fx.add("saturated = saturated.softclip")
fx.add("saturated = LeakDC.ar(saturated)")
fx.add("saturated = LPF.ar(saturated, 9000)")
fx.add("saturated = BLowShelf.ar(saturated, 150, 0.7, tubewarm * 2)")
fx.add("saturated = BPeakEQ.ar(saturated, 2500, 0.6, tubewarm * 1.5)")
fx.add("compressed = Compander.ar(saturated, saturated, 0.35, 1, 0.6, 0.003, 0.06, 1.3)")
fx.add("osc = XFade2.ar(dry, compressed * 0.8, tube * 2 - 1)")
fx.save()

# === ADVANCED TECHNO FX ===

# Pumper - sidechain simulation without routing (essential techno pump)
# A voir si garder ou pas, pas convaincu
fx = FxList.new("pumper", "pumper", {"pumper": 0.5, "pumprate": 4, "pumpattack": 0.005, "pumprel": 0.2, "pumpcurve": -4}, order=2, tag="volume")
fx.doc("Sidechain simulation - creates pumping effect synced to beat")
fx.add_var("dry")
fx.add_var("pumpEnv")
fx.add_var("rate")
fx.add("dry = osc")
fx.add("rate = pumprate / sus")
fx.add("pumpEnv = EnvGen.kr(Env.perc(pumpattack, pumprel, 1, pumpcurve), Impulse.kr(rate))")
fx.add("pumpEnv = 1 - (pumpEnv * pumper)")
fx.add("pumpEnv = pumpEnv.clip(0.05, 1)")
fx.add("osc = osc * pumpEnv")
fx.save()

# Transient shaper - attack/sustain control
fx = FxList.new("transient", "transient", {"transient": 0.5, "transattack": 1, "transsustain": 1, "transtime": 0.02}, order=2, tag="envelope")
fx.doc("Transient shaper - control attack punch and sustain level")
fx.add_var("dry")
fx.add_var("env")
fx.add_var("attack")
fx.add_var("sustain")
fx.add_var("shaped")
fx.add("dry = osc")
fx.add("env = Amplitude.ar(osc, transtime, 0.1)")
fx.add("attack = Amplitude.ar(osc, 0.001, transtime)")
fx.add("sustain = Amplitude.ar(osc, transtime * 2, 0.3)")
fx.add("shaped = osc * ((attack / (env + 0.001)).clip(0, 3) * (transattack - 1) + 1)")
fx.add("shaped = shaped * ((sustain / (env + 0.001)).clip(0, 2) * (transsustain - 1) + 1)")
fx.add("shaped = Limiter.ar(shaped, 0.95, 0.001)")
fx.add("osc = XFade2.ar(dry, shaped, transient * 2 - 1)")
fx.save()

# Multiband distortion - separate saturation for low/mid/high
fx = FxList.new("multicrush", "multicrush", {"multicrush": 0.5, "mclowdrive": 1.5, "mcmiddrive": 2, "mchighdrive": 1.8, "mclofreq": 200, "mchifreq": 3000}, order=2, tag="distortion")
fx.doc("Multiband distortion - independent saturation per frequency band")
fx.add_var("dry")
fx.add_var("low")
fx.add_var("mid")
fx.add_var("high")
fx.add_var("crushed")
fx.add("dry = osc")
fx.add("low = LPF.ar(osc, mclofreq)")
fx.add("mid = HPF.ar(LPF.ar(osc, mchifreq), mclofreq)")
fx.add("high = HPF.ar(osc, mchifreq)")
fx.add("low = (low * mclowdrive).softclip")
fx.add("mid = (mid * mcmiddrive)")
fx.add("mid = mid + (mid.cubed * 0.2)")
fx.add("mid = mid.fold(-0.9, 0.9)")
fx.add("high = (high * mchighdrive).tanh")
fx.add("high = LPF.ar(high, 12000)")
fx.add("crushed = low + mid + high")
fx.add("crushed = LeakDC.ar(crushed)")
fx.add("crushed = Limiter.ar(crushed, 0.95, 0.001)")
fx.add("osc = XFade2.ar(dry, crushed * 0.7, multicrush * 2 - 1)")
fx.save()

# Comb resonator - metallic/Karplus-Strong textures
fx = FxList.new("combres", "combres", {"combres": 0.5, "combfreq": 200, "combdecay": 0.3, "combspread": 0.01}, order=2, tag="filter")
fx.doc("Comb resonator - metallic textures and pitched resonance")
fx.add_var("dry")
fx.add_var("comb1")
fx.add_var("comb2")
fx.add_var("resonated")
fx.add_var("delayTime")
fx.add("dry = osc")
fx.add("delayTime = combfreq.reciprocal")
fx.add("comb1 = CombC.ar(osc, 0.1, delayTime.clip(0.0001, 0.1), combdecay)")
fx.add("comb2 = CombC.ar(osc, 0.1, (delayTime * (1 + combspread)).clip(0.0001, 0.1), combdecay * 0.9)")
fx.add("resonated = (comb1 + comb2) * 0.5")
fx.add("resonated = LPF.ar(resonated, 10000)")
fx.add("resonated = LeakDC.ar(resonated)")
fx.add("osc = XFade2.ar(dry, dry + (resonated * 0.5), combres * 2 - 1)")
fx.save()

# Rhythmic gate - trance gate synced to beat
fx = FxList.new("rgate", "rhythmgate", {"rgate": 0.5, "rgaterate": 4, "rgatewave": 0, 'beat_dur': 1}, order=2, tag="time")
fx.doc("Rhythmic gate - choppy textures synced to beat (wave: 0=square, 1=saw, 2=sine)")
fx.add_var("dry")
fx.add_var("gateEnv")
fx.add_var("rate")
fx.add("dry = osc")
fx.add("rate = rgaterate / beat_dur")
fx.add("gateEnv = Select.kr(rgatewave, [LFPulse.kr(rate, width: 0.5), LFSaw.kr(rate).range(0, 1), SinOsc.kr(rate).range(0, 1)])")
fx.add("osc = XFade2.ar(dry, osc * Lag.kr(gateEnv, 0.01), rgate * 2 - 1)")
fx.save()

# Stereo width - mono bass, wide highs
fx = FxList.new("stereowidth", "stereowidth", {"stereowidth": 0.5, "swfreq": 300, "swnarrow": 0, "swwide": 1.5}, order=2, tag="panning")
fx.doc("Stereo imager - mono bass, adjustable width for highs")
fx.add_var("dry")
fx.add_var("low")
fx.add_var("high")
fx.add_var("mid")
fx.add_var("side")
fx.add_var("widened")
fx.add("dry = osc")
fx.add("low = LPF.ar(osc, swfreq)")
fx.add("low = (low[0] + low[1]) * 0.5")
fx.add("low = low * (1 - swnarrow)")
fx.add("low = [low, low]")
fx.add("high = HPF.ar(osc, swfreq)")
fx.add("mid = (high[0] + high[1]) * 0.5")
fx.add("side = (high[0] - high[1]) * 0.5 * swwide")
fx.add("high = [mid + side, mid - side]")
fx.add("widened = low + high")
fx.add("osc = XFade2.ar(dry, widened, stereowidth * 2 - 1)")
fx.save()

# Bitrot - digital degradation, aliasing, glitchy artifacts
fx = FxList.new("bitrot", "bitrot", {"bitrot": 0.5, "rotbits": 8, "rotrate": 0.5, "rotjitter": 0.1}, order=2, tag="distortion")
fx.doc("Digital degradation - bit reduction with jitter and aliasing")
fx.add_var("dry")
fx.add_var("degraded")
fx.add_var("bits")
fx.add_var("sampleRate")
fx.add_var("jitter")
fx.add("dry = osc")
fx.add("bits = rotbits + (LFNoise1.kr(3).range(-1, 1) * rotjitter * 4)")
fx.add("bits = bits.clip(2, 16)")
fx.add("sampleRate = LinExp.kr(rotrate, 0, 1, 44100, 1000)")
fx.add("sampleRate = sampleRate + (LFNoise2.kr(5) * rotjitter * sampleRate * 0.3)")
fx.add("jitter = LFNoise0.kr(20).range(0.98, 1.02) ** (rotjitter * 5)")
fx.add("degraded = Latch.ar(osc, Impulse.ar(sampleRate * jitter))")
fx.add("degraded = degraded.round(2.pow(bits.neg))")
fx.add("degraded = (degraded * 1.2).fold(-0.95, 0.95)")
fx.add("degraded = LeakDC.ar(degraded)")
fx.add("osc = XFade2.ar(dry, degraded, bitrot * 2 - 1)")
fx.save()

# Feedback delay - self-oscillating, dub-style with filtering
fx = FxList.new("fbdelay", "fbdelay", {"fbdelay": 0.5, "fbtime": 0.25, "fbfeed": 0.7, "fbcutoff": 3000, "fbspread": 0.02, "beat_dur": 1}, order=2, tag="time")
fx.doc("Feedback delay with filtering - self-oscillating dub delays")
fx.add_var("dry")
fx.add_var("delayed")
fx.add_var("leftDelay")
fx.add_var("rightDelay")
fx.add_var("fb")
fx.add_var("delTime")
fx.add("dry = osc")
fx.add("delTime = fbtime * beat_dur")
fx.add("fb = LocalIn.ar(2) * fbfeed")
fx.add("fb = HPF.ar(fb, 80)")
fx.add("fb = LPF.ar(fb, fbcutoff)")
fx.add("fb = (fb * 1.1).softclip")
fx.add("leftDelay = DelayC.ar(osc[0] + fb[1], 2, delTime.clip(0.001, 2))")
fx.add("rightDelay = DelayC.ar(osc[1] + fb[0], 2, (delTime * (1 + fbspread)).clip(0.001, 2))")
fx.add("LocalOut.ar([leftDelay, rightDelay])")
fx.add("delayed = [leftDelay, rightDelay] * 0.7")
fx.add("osc = XFade2.ar(dry, dry + delayed, fbdelay * 2 - 1)")
fx.save()

# Freeze - spectral freeze for drone textures
fx = FxList.new("freeze", "spectralfreeze", {"freeze": 0.5, "freezemix": 0.5, "freezerand": 0}, order=2, tag="time")
fx.doc("Spectral freeze - captures and holds spectrum for drones")
fx.add_var("dry")
fx.add_var("chain")
fx.add_var("frozen")
fx.add("dry = osc")
fx.add("chain = FFT(Array.fill(2, { LocalBuf(2048, 1) }), osc)")
fx.add("chain = PV_MagFreeze(chain, freeze > 0.5)")
fx.add("chain = PV_MagSmear(chain, freezerand * 10)")
fx.add("frozen = IFFT(chain)")
fx.add("frozen = LeakDC.ar(frozen)")
fx.add("osc = XFade2.ar(dry, (dry * (1 - freezemix)) + (frozen * freezemix), freeze * 2 - 1)")
fx.save()

# Decimate - extreme sample rate + bit reduction
fx = FxList.new("decimate", "decimate", {"decimate": 0.5, "decbits": 4, "decrate": 4000, "decsmooth": 0}, order=2, tag="distortion")
fx.doc("Extreme decimation - aggressive lo-fi destruction")
fx.add_var("dry")
fx.add_var("destroyed")
fx.add_var("preFiltered")
fx.add("dry = osc")
fx.add("preFiltered = LPF.ar(osc, decrate * 0.4)")
fx.add("destroyed = Latch.ar(preFiltered, Impulse.ar(decrate))")
fx.add("destroyed = destroyed.round(2.pow(decbits.neg))")
fx.add("destroyed = Select.ar(decsmooth > 0, [destroyed, LPF.ar(destroyed, decrate * decsmooth.linlin(0, 1, 0.5, 2))])")
fx.add("destroyed = (destroyed * 2).wrap(-0.9, 0.9)")
fx.add("destroyed = LeakDC.ar(destroyed)")
fx.add("osc = XFade2.ar(dry, destroyed * 0.8, decimate * 2 - 1)")
fx.save()

# === GLITCH / STUTTER FX ===

# Glitch - combined random effects (crush, pitch, reverse)
fx = FxList.new("glitch", "glitch", {"glitch": 0.5, "glitchrate": 8, "glitchdepth": 0.5, "glitchcrush": 0.3, "glitchchance": 0.5, "beat_dur": 1}, order=2, tag="modulation")
fx.doc("Random glitch - combines crush, pitch shift, and stutters")
fx.add_var("dry")
fx.add_var("glitched")
fx.add_var("trig")
fx.add_var("rate")
fx.add_var("shouldGlitch")
fx.add_var("crushed")
fx.add_var("pitched")
fx.add_var("bits")
fx.add("dry = osc")
fx.add("rate = glitchrate / beat_dur")
fx.add("trig = Impulse.kr(rate)")
fx.add("shouldGlitch = TRand.kr(0, 1, trig) < glitchchance")
fx.add("bits = TRand.kr(4, 12, trig)")
fx.add("crushed = Latch.ar(osc, Impulse.ar(TRand.kr(2000, 8000, trig)))")
fx.add("crushed = crushed.round(2.pow(bits.neg))")
fx.add("pitched = PitchShift.ar(osc, 0.1, TRand.kr(0.8, 1.2, trig) ** (glitchdepth * 2), 0, 0.01)")
fx.add("glitched = SelectX.ar(glitchcrush, [pitched, crushed])")
fx.add("glitched = Select.ar(shouldGlitch, [osc, glitched])")
fx.add("glitched = LeakDC.ar(glitched)")
fx.add("osc = XFade2.ar(dry, glitched, glitch * 2 - 1)")
fx.save()

# Tape Stop - slowdown/speedup effect
fx = FxList.new("tstop", "tapestop", {"tstop": 0.5, "tstoptime": 0.5, "tstopcurve": -4, "tstopdir": 0, "sus": 1}, order=2, tag="time")
fx.doc("Tape stop - pitch drops to zero (or speeds up) like stopping tape")
fx.add_var("dry")
fx.add_var("rate")
fx.add_var("stopped")
fx.add_var("startRate")
fx.add_var("endRate")
fx.add("dry = osc")
fx.add("startRate = Select.kr(tstopdir, [1, 0.1])")
fx.add("endRate = Select.kr(tstopdir, [0.1, 1])")
fx.add("rate = EnvGen.kr(Env([startRate, endRate], [tstoptime * sus], tstopcurve))")
fx.add("stopped = PitchShift.ar(osc, 0.1, rate, 0, 0.01)")
fx.add("stopped = stopped * rate.sqrt")
fx.add("osc = XFade2.ar(dry, stopped, tstop * 2 - 1)")
fx.save()

# Drift - humanize timing with subtle random variations
fx = FxList.new("drift", "drift", {"drift": 0.5, "driftspeed": 2, "driftdepth": 0.02, "driftsmooth": 0.5}, order=2, tag="envelope")
fx.doc("Timing drift - adds subtle humanized timing variations")
fx.add_var("dry")
fx.add_var("drifted")
fx.add_var("delayMod")
fx.add_var("maxDelay")
fx.add("dry = osc")
fx.add("maxDelay = 0.05")
fx.add("delayMod = LFNoise2.kr(driftspeed).range(0, driftdepth * maxDelay)")
fx.add("delayMod = Lag.kr(delayMod, driftsmooth * 0.1)")
fx.add("drifted = DelayC.ar(osc, maxDelay, delayMod)")
fx.add("osc = XFade2.ar(dry, drifted, drift * 2 - 1)")
fx.save()

# Time-stretch FX - PitchShift-based time manipulation (pitch preserved)
fx = FxList.new("tstretch", "timeStretchFx", {"tstretch": 1, "tstretchsize": 0.2}, order=2, tag="granular")
fx.doc("PitchShift-based time stretch on any signal, pitch preserved")
fx.add_var("stretched")
fx.add_var("xfade")
fx.add("stretched = PitchShift.ar(osc, tstretchsize, 1, 0, 0.004)")
fx.add("xfade = (1 - tstretch).abs.min(1)")
fx.add("osc = XFade2.ar(osc, stretched, xfade * 2 - 1)")
fx.save()

# Resonator Bank (6 resonators)
fx = FxList.new("resonbank", "resonbank", {
    "resonbank": 0, "rbfreq": 200, "rbdecay": 0.5, "rbspread": 1.0
}, order=2, tag="modulation", useControl=False)
fx.doc("6-resonator bank (rbspread=1 harmonic, other = inharmonic)")
fx.add_var("resonated")
fx.add_var("dry")
fx.add("dry = osc")
fx.add("resonated = Ringz.ar(osc, rbfreq * (1 ** rbspread), rbdecay) + Ringz.ar(osc, rbfreq * (2 ** rbspread), rbdecay) + Ringz.ar(osc, rbfreq * (3 ** rbspread), rbdecay) + Ringz.ar(osc, rbfreq * (4 ** rbspread), rbdecay) + Ringz.ar(osc, rbfreq * (5 ** rbspread), rbdecay) + Ringz.ar(osc, rbfreq * (6 ** rbspread), rbdecay)")
fx.add("resonated = LeakDC.ar(resonated * 0.5)")
fx.add("resonated = Limiter.ar(resonated, 0.95)")
fx.add("osc = SelectX.ar(resonbank, [dry, dry + (resonated * 0.5)])")
fx.save()

# Clean Octaver - PitchShift-based sub and octave-up
fx = FxList.new("octclean", "octclean", {"octclean": 0, "ocsub": 0.5, "ocup": 0.3}, order=1, tag="pitch")
fx.doc("Clean octaver via PitchShift (sub -1oct, up +1oct)")
fx.add_var("dry")
fx.add_var("sub")
fx.add_var("up")
fx.add("dry = osc")
fx.add("sub = PitchShift.ar(osc, 0.1, 0.5, 0, 0.004)")
fx.add("up = PitchShift.ar(osc, 0.05, 2.0, 0, 0.004)")
fx.add("osc = osc + (sub * ocsub) + (up * ocup)")
fx.add("osc = XFade2.ar(dry, LeakDC.ar(osc), octclean * 2 - 1)")
fx.save()

# Dynamic Fuzz - envelope-shaped distortion that breathes with each note
fx = FxList.new("dynfuzz", "dynfuzz", {"dynfuzz": 0, "dfgain": 1, "dfatk": 0.005, "dfdec": 0.3, "dftone": 0.6}, order=2, tag="distortion")
fx.doc("Fuzz with per-note envelope shaping - pumps on repetitive patterns")
fx.add_var("dry")
fx.add_var("trig")
fx.add_var("env")
fx.add_var("driven")
fx.add_var("fuzzed")
fx.add("dry = osc")
fx.add("trig = Trig1.kr(Amplitude.kr(osc, 0.001, 0.05) > 0.02, 0.01)")
fx.add("env = Decay2.kr(trig, dfatk, dfdec)")
fx.add("driven = osc * (1 + (env * dfgain))")
fx.add("fuzzed = driven.tanh")
fx.add("fuzzed = BPeakEQ.ar(fuzzed, 900, 0.7, dftone.clip(0, 1) * 2)")
fx.add("fuzzed = LPF.ar(fuzzed, 3000 + (dftone.clip(0, 1) * 7000))")
fx.add("fuzzed = LeakDC.ar(fuzzed)")
fx.add("osc = XFade2.ar(dry, fuzzed * 0.75, dynfuzz * 2 - 1)")
fx.save()

# Cheap Reverb - Schroeder topology (4 combs + 2 allpass diffusers)
fx = FxList.new("cheapverb", "cheapverb", {"cheapverb": 0, "cvdecay": 1.5, "cvdamp": 0.5}, order=2, tag="reverb")
fx.doc("CPU-light delay-based reverb (Schroeder topology)")
fx.add_var("dry")
fx.add_var("src")
fx.add_var("c1")
fx.add_var("c2")
fx.add_var("c3")
fx.add_var("c4")
fx.add_var("wet")
fx.add_var("lpf")
fx.add("dry = osc")
fx.add("src = HPF.ar(osc, 80)")
fx.add("lpf = 2000 + ((1 - cvdamp) * 8000)")
fx.add("c1 = LPF.ar(CombC.ar(src, 0.05, 0.0297, cvdecay), lpf)")
fx.add("c2 = LPF.ar(CombC.ar(src, 0.05, 0.0371, cvdecay * 0.9), lpf)")
fx.add("c3 = LPF.ar(CombC.ar(src, 0.05, 0.0411, cvdecay * 1.1), lpf)")
fx.add("c4 = LPF.ar(CombC.ar(src, 0.05, 0.0437, cvdecay * 0.95), lpf)")
fx.add("wet = c1 + c2 + c3 + c4")
fx.add("wet = AllpassC.ar(wet, 0.02, 0.005, 0.08)")
fx.add("wet = AllpassC.ar(wet, 0.02, 0.012, 0.06)")
fx.add("wet = LeakDC.ar(wet * 0.25)")
fx.add("osc = XFade2.ar(dry, wet, cheapverb * 2 - 1)")
fx.save()


## Keep this fx at the end to force the order and use at the end of fx chain. Use other filter for filtering before.
fx = FxList.new('hpf','highPassFilter', {'hpf': 0, 'hpr': 1}, order=2, tag="filter")
fx.doc("Highpass filter")
fx.add('osc = RHPF.ar(osc, hpf, hpr)')
fx.save()

fx = FxList.new('lpf','lowPassFilter', {'lpf': 0, 'lpr': 1}, order=2, tag="filter")
fx.add('osc = RLPF.ar(osc, lpf, lpr)')
fx.save()

Effect.server.setFx(FxList)
